module(
    name = "northwind_example",
    version = "0.0.0",
)

bazel_dep(name = "contrib_rules_jvm", version = "0.31.1")
bazel_dep(name = "rules_jvm_external", version = "6.9")
bazel_dep(name = "rules_jooq_flyway_codegen", version = "0.0.0")
local_path_override(
    module_name = "rules_jooq_flyway_codegen",
    path = "../..",
)

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "com.google.code.gson:gson:2.8.6",
        "com.sparkjava:spark-core:2.9.1",
        "com.zaxxer:HikariCP:3.4.5",
        "mysql:mysql-connector-java:8.0.21",
        "org.assertj:assertj-core:3.27.6",
        "org.flywaydb:flyway-core",
        "org.flywaydb:flyway-database-postgresql",
        "org.flywaydb:flyway-mysql",
        "org.jooq:jooq",
        "org.jooq:jooq-codegen",
        "org.jooq:jooq-meta",
        "org.junit.jupiter:junit-jupiter-api",
        "org.junit.jupiter:junit-jupiter-engine",
        "org.junit.platform:junit-platform-launcher",
        "org.junit.platform:junit-platform-reporting",
        "org.slf4j:slf4j-simple:1.7.30",
        "org.testcontainers:testcontainers",
        "org.testcontainers:testcontainers-mysql",
        "org.xerial:sqlite-jdbc:3.32.3.2",
    ],
    boms = [
        "org.junit:junit-bom:6.0.2",
        "io.dropwizard.flywaydb:flyway-bom:11.17.2",
        "org.jooq:jooq-bom:3.20.11",
        "org.testcontainers:testcontainers-bom:2.0.3",
    ],
    fetch_sources = True,
    lock_file = "//:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    strict_visibility = True,
)
use_repo(maven, "maven")
