module(
    name = "rules_jooq_flyway_codegen",
    bazel_compatibility = [">=7.0.0"],
)

bazel_dep(name = "contrib_rules_jvm", version = "0.31.1")
bazel_dep(name = "rules_jvm_external", version = "6.9")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "rules_jooq_flyway_codegen_maven",
    artifacts = [
        "com.beust:jcommander:1.82",
        "mysql:mysql-connector-java:8.0.21",
        "org.flywaydb:flyway-commandline:11.17.2",
        "org.flywaydb:flyway-core",
        "org.flywaydb:flyway-database-postgresql",
        "org.flywaydb:flyway-mysql",
        "org.jooq:jooq",
        "org.jooq:jooq-codegen",
        "org.jooq:jooq-meta",
        "org.mariadb.jdbc:mariadb-java-client:2.6.2",
        "org.postgresql:postgresql:42.2.14",
        "org.testcontainers:testcontainers",
        "org.testcontainers:testcontainers-jdbc",
        "org.testcontainers:testcontainers-mariadb",
        "org.testcontainers:testcontainers-mysql",
        "org.testcontainers:testcontainers-postgresql",
        "org.xerial:sqlite-jdbc:3.32.3.2",
    ],
    boms = [
        "io.dropwizard.flywaydb:flyway-bom:11.17.2",
        "org.jooq:jooq-bom:3.20.11",
        "org.testcontainers:testcontainers-bom:2.0.3",
    ],
    fetch_sources = True,
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    #        lock_file = "//:rules_jvm_external_deps_install.json",
    strict_visibility = True,
)
maven.artifact(
    name = "rules_jooq_flyway_codegen_maven",
    artifact = "json-smart",
    force_version = True,
    group = "net.minidev",
    version = "2.5.2",
)
use_repo(maven, "rules_jooq_flyway_codegen_maven")
