load("@contrib_rules_jvm//java:defs.bzl", "java_binary", "java_library")
load("@rules_jvm_external//:defs.bzl", "artifact")

java_library(
    name = "codegen_lib",
    srcs = [
        "JdbcProvider.java",
        "JooqBazelCodegen.java",
        "SqliteJdbcProvider.java",
        "TestContainersJdbcProvider.java",
        "ZipUtil.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        artifact("mysql:mysql-connector-java", "rules_jooq_flyway_codegen_maven"),
        artifact("org.flywaydb:flyway-core", "rules_jooq_flyway_codegen_maven"),
        artifact("org.flywaydb:flyway-database-postgresql", "rules_jooq_flyway_codegen_maven"),
        artifact("org.flywaydb:flyway-mysql", "rules_jooq_flyway_codegen_maven"),
        artifact("org.jooq:jooq", "rules_jooq_flyway_codegen_maven"),
        artifact("org.jooq:jooq-codegen", "rules_jooq_flyway_codegen_maven"),
        artifact("org.jooq:jooq-meta", "rules_jooq_flyway_codegen_maven"),
        artifact("org.mariadb.jdbc:mariadb-java-client", "rules_jooq_flyway_codegen_maven"),
        artifact("org.postgresql:postgresql", "rules_jooq_flyway_codegen_maven"),
        artifact("org.testcontainers:testcontainers-mariadb", "rules_jooq_flyway_codegen_maven"),
        artifact("org.testcontainers:testcontainers-mysql", "rules_jooq_flyway_codegen_maven"),
        artifact("org.testcontainers:testcontainers-postgresql", "rules_jooq_flyway_codegen_maven"),
        artifact("org.testcontainers:testcontainers", "rules_jooq_flyway_codegen_maven"),
        artifact("org.testcontainers:testcontainers-jdbc", "rules_jooq_flyway_codegen_maven"),
        artifact("org.xerial:sqlite-jdbc", "rules_jooq_flyway_codegen_maven"),
    ],
)
